trigger:
- master

pool:
  name: 'Default'  # Указываем пул Default, который является стандартным в Azure DevOps

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use latest 3.x version'

- script: |
    python -m pip install --upgrade pip
    pip install --no-cache-dir -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest --disable-warnings
  displayName: 'Run pytest tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'pytest results'
  condition: succeededOrFailed()
